import { useState, useRef, useEffect } from "react";
import { Bot, Send, Sparkles, RefreshCw, Zap, ShieldCheck, Activity, CheckCircle2, MessageSquare, AlertTriangle, FileText, Download, Navigation, Thermometer, Mic } from "lucide-react";
import { processIncidentWithBackend, BackendIncidentResult } from "@/lib/api";
import { CustomFlowchart } from "./CustomFlowchart";
import { LiveGlobe } from "./LiveGlobe";

type ChatMessage = {
  id: string;
  sender: "user" | "ai";
  agentName?: string;
  text?: string;
  apiData?: BackendIncidentResult;
  time: string;
  badge?: string;
  flowchart?: string;
  activeTab?: "report" | "flow";
};

const initialMessages: ChatMessage[] = [
  {
    id: "m-1",
    sender: "ai",
    agentName: "Neural AI Commander",
    text: "Welcome Commander. I am your AI Emergency Assistant. You can ask me any question about live disaster operations, request quick status summaries, or trigger fast-access questions.",
    time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    badge: "System Ready",
    activeTab: "report"
  },
];

export function AIAgentChatView() {
  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [input, setInput] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const [activeGlobeCoords, setActiveGlobeCoords] = useState<{lat?: number, lng?: number}>({});
  const chatEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isThinking]);

  const [isListening, setIsListening] = useState(false);

  const handleDownloadIRSForm = () => {
    const text = "IRS FORM 201 - INCIDENT BRIEFING\n\nIncident Name: Emergency Operations\nDate/Time: " + new Date().toLocaleString() + "\n\n1. Situation Summary:\nHigh severity incidents being monitored by multi-agent system.\n\n2. Current Organization:\n- AI Commander (Dispatcher)\n- Police Agent\n- Medical Agent\n- Fire & Rescue Agent\n\n[OFFICIAL DOCUMENT GENERATED BY MINDWEAVERS AI]";
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "IRS_Form_201_Emergency.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleInstantMedicalReport = () => {
    const aiMsg: ChatMessage = {
      id: `ai-${Date.now()}`,
      sender: "ai",
      agentName: "MINDWEAVERS AI",
      text: "Instant Medical Status Report: Currently there are 14 ICU beds available across city hospitals. 6 Red-Triage beds have been pre-reserved at Metro General for high-severity incoming casualties. Ambulance fleet readiness is at 94%.",
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
      badge: "Instant Telemetry"
    };
    setMessages(prev => [...prev, aiMsg]);
  };

  const handleSend = async (textQuery?: string) => {
    const query = textQuery || input;
    if (!query.trim()) return;

    const userMsg: ChatMessage = {
      id: `u-${Date.now()}`,
      sender: "user",
      text: query,
      time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
    };

    setMessages((prev) => [...prev, userMsg]);
    if (!textQuery) setInput("");
    setIsThinking(true);

    try {
      const apiRes = await processIncidentWithBackend(query);
      
      let aiMsg: ChatMessage;
      
      if (apiRes) {
        if (apiRes.latitude && apiRes.longitude) {
          setActiveGlobeCoords({ lat: apiRes.latitude, lng: apiRes.longitude });
        }
        aiMsg = {
          id: `ai-${Date.now()}`,
          sender: "ai",
          agentName: "MINDWEAVERS AI",
          apiData: apiRes,
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
          badge: "Neural Verified",
          flowchart: apiRes.flowchart_mermaid || "",
          activeTab: "report"
        };
      } else {
        aiMsg = {
          id: `ai-${Date.now()}`,
          sender: "ai",
          agentName: "MINDWEAVERS AI",
          text: `AI Commander Analysis for "${query}": Telemetry evaluated across Fire, Medical, Police, and Traffic multi-agent pipelines. All operational metrics within normal safety bounds.`,
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
          badge: "System Default",
          activeTab: "report"
        };
      }

      setMessages((prev) => [...prev, aiMsg]);
    } catch (e) {
      console.error(e);
      setMessages((prev) => [...prev, {
          id: `ai-${Date.now()}`,
          sender: "ai",
          agentName: "MINDWEAVERS AI",
          text: "Error connecting to AI Backend.",
          time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
          activeTab: "report"
      }]);
    } finally {
      setIsThinking(false);
    }
  };

  const toggleTab = (msgId: string, tab: "report" | "flow") => {
    setMessages(prev => prev.map(m => m.id === msgId ? { ...m, activeTab: tab } : m));
  };

  return (
    <div className="grid gap-6 lg:grid-cols-12 rise-in h-[85vh] bg-[#0B0C10] p-4 rounded-xl text-slate-300">
      
      {/* Left Sidebar */}
      <div className="lg:col-span-3 flex flex-col gap-6">
        {/* Brand Card */}
        <div className="p-6 rounded-2xl border border-purple-900/50 bg-[#12141D] flex flex-col items-center justify-center relative overflow-hidden">
          <div className="absolute inset-0 opacity-20 bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-600 via-transparent to-transparent pointer-events-none"></div>
          
          <div className="p-4 rounded-full bg-purple-900/40 border border-purple-500/30 mb-4 z-10">
            <Bot className="size-8 text-purple-400" />
          </div>
          <h2 className="text-sm font-extrabold text-white tracking-widest z-10">MINDWEAVERS AI</h2>
          <p className="text-[10px] text-purple-400/70 uppercase tracking-widest mb-4 z-10">Disaster Copilot v2.1</p>
          <div className="flex items-center gap-2 text-[10px] text-emerald-400 mb-6 z-10">
            <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></div> Ready for command
          </div>

          <button 
            onClick={() => setIsListening(!isListening)}
            className={`flex items-center gap-2 px-6 py-2 rounded-full border text-xs font-semibold transition-colors z-10 w-full justify-center ${
              isListening 
                ? "bg-rose-950/60 border-rose-500/60 text-rose-300 shadow-[0_0_15px_rgba(225,29,72,0.3)] animate-pulse"
                : "bg-transparent border-purple-500/40 text-purple-300 hover:bg-purple-900/40"
            }`}
          >
            {isListening ? (
              <><div className="size-2 rounded-full bg-rose-500 animate-ping"></div> Listening...</>
            ) : (
              <><Mic className="size-3.5" /> Enable Voice</>
            )}
          </button>
        </div>

        {/* Quick Actions */}
        <div className="p-5 rounded-2xl border border-purple-900/50 bg-[#12141D] flex-1">
          <h3 className="text-xs font-bold text-purple-400/70 tracking-widest uppercase mb-4">Quick Actions</h3>
          <div className="space-y-2">
            {[
              { icon: FileText, label: "Generate Incident Summary Report", color: "text-blue-400", onClick: () => handleSend("Generate a complete Incident Summary Report of all current active operations.") },
              { icon: Download, label: "Download IRS Form 201 (Official)", color: "text-emerald-400", onClick: handleDownloadIRSForm },
              { icon: Navigation, label: "Optimize Evacuation Routes", color: "text-amber-400", onClick: () => handleSend("Optimize evacuation routes for the current major incident.") },
              { icon: Activity, label: "Check Available ICU Beds", color: "text-pink-400", onClick: handleInstantMedicalReport },
              { icon: Thermometer, label: "Analyze High Severity Fires", color: "text-orange-400", onClick: () => handleSend("Analyze all high severity fire incidents and their containment status.") },
            ].map((action, idx) => (
              <button 
                key={idx} 
                onClick={action.onClick}
                className="w-full text-left p-3 rounded-xl hover:bg-white/5 transition-colors flex items-start gap-3 group"
              >
                <action.icon className={`size-4 mt-0.5 ${action.color}`} />
                <span className="text-xs font-semibold text-slate-300 group-hover:text-white transition-colors">{action.label}</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Middle Column: Main Chat */}
      <div className="lg:col-span-6 flex flex-col rounded-2xl border border-purple-900/50 bg-[#12141D] overflow-hidden relative">
        <div className="absolute inset-0 pointer-events-none opacity-[0.03] bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
        
        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6 z-10 scrollbar-thin scrollbar-thumb-purple-900/50">
          {messages.map((m) => (
            <div key={m.id} className={`flex flex-col ${m.sender === "user" ? "items-end" : "items-start"}`}>
              {m.sender === "user" ? (
                <div className="max-w-[80%] p-3.5 rounded-2xl rounded-br-sm bg-purple-600 text-white text-sm font-medium shadow-lg">
                  {m.text}
                </div>
              ) : (
                <div className="w-full max-w-[95%]">
                  {/* AI Response Tabs */}
                  {m.apiData && (
                    <div className="flex items-center gap-1 mb-2 pl-2">
                      <button onClick={() => toggleTab(m.id, "report")} className={`px-4 py-1.5 rounded-t-lg text-xs font-bold transition-colors ${m.activeTab === "report" ? "bg-purple-900/40 text-purple-200 border-t border-x border-purple-500/30" : "text-slate-500 hover:text-slate-300"}`}>
                        📄 Report
                      </button>
                      <button onClick={() => toggleTab(m.id, "flow")} className={`px-4 py-1.5 rounded-t-lg text-xs font-bold transition-colors ${m.activeTab === "flow" ? "bg-purple-900/40 text-purple-200 border-t border-x border-purple-500/30" : "text-slate-500 hover:text-slate-300"}`}>
                        🔄 Flow
                      </button>
                    </div>
                  )}

                  <div className={`p-5 rounded-2xl rounded-tl-sm border border-purple-500/20 bg-purple-950/10 backdrop-blur-sm shadow-xl ${m.apiData ? "rounded-tl-none" : ""}`}>
                    
                    {/* Render Text (if no apiData) */}
                    {m.text && !m.apiData && (
                      <p className="text-sm text-slate-200 leading-relaxed">{m.text}</p>
                    )}

                    {/* Render Structured API Data */}
                    {m.apiData && m.activeTab === "report" && (
                      <div className="space-y-4">
                        {/* Incident Classification Block */}
                        <div className="p-4 rounded-xl bg-[#1A1D27] border border-blue-900/30">
                          <h4 className="text-xs font-extrabold text-blue-400 mb-3 flex items-center gap-2"><FileText className="size-3.5" /> Incident Classification</h4>
                          <div className="space-y-1.5 text-xs">
                            <p><span className="text-slate-500 font-semibold w-24 inline-block">Type:</span> <span className="text-slate-200">{m.apiData.incident_type}</span></p>
                            <p><span className="text-slate-500 font-semibold w-24 inline-block">Severity:</span> <span className="text-slate-200">{m.apiData.severity}</span></p>
                            <p><span className="text-slate-500 font-semibold w-24 inline-block">Location:</span> <span className="text-slate-200">{m.apiData.location}</span></p>
                            <p><span className="text-slate-500 font-semibold w-24 inline-block">Casualties:</span> <span className="text-slate-200">Monitoring</span></p>
                          </div>
                          <div className="mt-4 p-3 rounded-lg bg-blue-950/30 border border-blue-900/40 text-xs font-bold text-blue-300 flex items-center gap-2">
                            <Zap className="size-3.5 text-blue-400" /> Strategic Priority: {m.apiData.strategic_priority}
                          </div>
                        </div>

                        {/* Department Responses */}
                        {m.apiData.department_responses && Object.entries(m.apiData.department_responses).map(([dept, details]: [string, any]) => {
                          const isFire = dept.includes("Fire");
                          const color = isFire ? "orange" : dept.includes("Medical") ? "emerald" : "indigo";
                          return (
                            <div key={dept} className={`p-4 rounded-xl bg-[#1A1D27] border border-${color}-900/30`}>
                              <h4 className={`text-xs font-extrabold text-${color}-400 mb-2 flex items-center gap-2`}>
                                <Bot className="size-3.5" /> {dept} Response
                              </h4>
                              <p className="text-xs text-slate-300 italic">"{details.action_summary || "Units deployed."}"</p>
                            </div>
                          )
                        })}

                        {/* NDMA CAP Alert (Mock styling for severity) */}
                        {m.apiData.severity.toLowerCase().includes("high") || m.apiData.severity.toLowerCase().includes("severe") || m.apiData.severity.toLowerCase().includes("critical") ? (
                          <div className="p-4 rounded-xl bg-orange-950/20 border border-orange-900/50 relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-1 h-full bg-orange-500"></div>
                            <div className="flex items-center justify-between mb-4">
                              <span className="text-[10px] font-extrabold tracking-widest text-orange-500 uppercase flex items-center gap-2">
                                <AlertTriangle className="size-3.5" /> NDMA CAP ALERT - ITU-T X.1303
                              </span>
                              <div className="flex gap-2">
                                <span className="px-2 py-0.5 rounded bg-orange-600 text-white text-[9px] font-bold">ACTUAL</span>
                                <span className="px-2 py-0.5 rounded border border-orange-600/50 text-orange-500 text-[9px] font-bold">ALERT</span>
                              </div>
                            </div>
                            <p className="text-sm font-bold text-white mb-4">Severe {m.apiData.incident_type} Alert — {m.apiData.location}</p>
                            <div className="flex justify-between text-[9px] text-orange-500/70 font-mono border-t border-orange-900/30 pt-2">
                              <span>IDENTIFIER<br/>IN-NDMA-{Date.now().toString().slice(-10)}</span>
                              <span>SENDER<br/>SDRF - State Disaster Response Force</span>
                              <span>SENT<br/>{new Date().toLocaleString()}</span>
                            </div>
                          </div>
                        ) : null}
                      </div>
                    )}

                    {/* Render Flowchart */}
                    {m.apiData && m.activeTab === "flow" && (
                      <div className="rounded-xl overflow-hidden mt-2">
                        <CustomFlowchart data={m.apiData} />
                      </div>
                    )}

                  </div>
                </div>
              )}
            </div>
          ))}

          {isThinking && (
            <div className="flex items-center gap-3 text-xs font-bold text-purple-400 p-4 max-w-xs">
              <RefreshCw className="size-4 animate-spin" /> Analyzing disaster telemetry...
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-4 bg-[#1A1D27] border-t border-purple-900/30 z-10">
          <div className="flex items-center gap-3 bg-[#0B0C10] p-2 pl-4 rounded-xl border border-purple-900/50 focus-within:border-purple-500/50 transition-colors">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
              placeholder="Ask the AI Copilot anything about the disaster situation..."
              className="flex-1 bg-transparent text-sm font-medium text-white placeholder:text-slate-600 focus:outline-none"
            />
            <button
              onClick={() => handleSend()}
              disabled={isThinking || !input.trim()}
              className="px-6 py-2.5 rounded-lg bg-blue-600/20 text-blue-400 hover:bg-blue-600/30 disabled:opacity-50 text-xs font-extrabold flex items-center gap-2 transition-colors border border-blue-500/20"
            >
              <Zap className="size-3.5 fill-blue-400" /> Send
            </button>
          </div>
        </div>
      </div>

      {/* Right Column: Globe */}
      <div className="lg:col-span-3 flex flex-col rounded-2xl border border-purple-900/50 bg-[#12141D] p-5 relative overflow-hidden">
        <h3 className="text-[10px] font-extrabold text-slate-400 tracking-[0.2em] uppercase mb-4 z-10">Live Geolocation</h3>
        
        <div className="flex-1 -mx-5 relative z-0 flex items-center justify-center">
          <LiveGlobe latitude={activeGlobeCoords.lat} longitude={activeGlobeCoords.lng} />
        </div>
        
        <div className="absolute bottom-5 left-5 right-5 z-10">
           {activeGlobeCoords.lat ? (
             <div className="p-3 rounded-xl bg-purple-950/40 border border-purple-500/20 backdrop-blur-md">
               <p className="text-[10px] text-purple-300 font-mono flex items-center gap-2"><Navigation className="size-3" /> Target Acquired</p>
               <p className="text-xs text-white font-bold mt-1">{activeGlobeCoords.lat.toFixed(4)}°, {activeGlobeCoords.lng?.toFixed(4)}°</p>
             </div>
           ) : (
             <div className="p-3 rounded-xl bg-slate-900/40 border border-slate-700/50 backdrop-blur-md">
               <p className="text-[10px] text-slate-400 font-mono">Awaiting Target Coordinates...</p>
             </div>
           )}
        </div>
      </div>
    </div>
  );
}
